---
# vars:
#   fapolicy_state: <started/stopped/restarted>

- name: Install and configure fapolicyd
  hosts: "{{ _hosts }}"
  become: true
  tasks:
    - name: Install fapolicyd
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.package:
        name: fapolicyd
        state: present

    - name: Configure fapolicyd service
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.service:
        name: fapolicyd
        state: "{{ fapolicy_state }}"
        enabled: true
