- name: Manage ServiceNow incident 
  hosts: localhost
  connection: local
  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: admin
        short_description: Badness detected.
        description: A security event has been detemined to require immediate attention.
        impact: high
        urgency: high 
      register: incident
      check_mode: false
      tags:
        - create
  
    - name: Export incident data for AAP workflow
      ansible.builtin.set_stats:
        data:
          incident_record_number: "{{ incident.record.number }}"
      tags:
        - create
  
    - name: Update incident 
      servicenow.itsm.incident:
        number: "{{ ansible_eda.event.payload.number }}"
        state: in_progress
        other:
          comments: "Ansible needs your help rescuing puppies!\n
          Quick go to [code]<a href=\"https://ctrl.lab.cheeseburgia.com/#/jobs/workflow/{{ awx_workflow_job_id }}/output\" target=\"_blank\">Ansible Controller</a>[/code]"
      tags:
        - update

    - name: Close incident
      servicenow.itsm.incident:
        number: "{{ ansible_eda.event.payload.number }}"
        state: resolved
        close_code: "Solved Remotely (Permanently)"
        close_notes: "Closed"
        caller: "admin"
        description: "Puppes have been protected, at least for now."
        short_description: "{{ ansible_date_time.iso8601_micro }}"
      when:
        - ansible_eda.event.payload.number is defined
      tags:
        - close
  
    - name: Debug output for created incident
      ansible.builtin.debug:
        msg: 
          - "{{ incident | default(ansible_eda.event) }}"
          - "{{ incident.record.number |default(ansible_eda.event.payload.number) }}"
 
