---
# vars:
#   ansible_hostname: <hostname LB points to>
#   lb_domain: <load balancer domain>
#   lb_protocol: <load blancer protocol>

- name: Generate and configure external load balancer
  hosts: "{{ _hosts }}"
  become: true
  tasks:
    - name: Build configuration
      ansible.builtin.template:
        src: server.j2
        dest: /etc/nginx/snippets/webservers.conf
      register: config

    - name: Restart load balancer when config is changed
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: config.changed
