---
- name: Scan webapp files
  ansible.builtin.stat:
    path: "{{ item.path }}"
    get_checksum: true
  loop: "{{ scan_vars }}"
  register: app_files_stat

- name: Debug register output
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: app_files_stat.results 

- name: Assert checksums are valid
  ansible.builtin.assert:
    that:
      - item.0.stat.checksum == item.1.checksum
  loop: "{{ app_files_stat.results | zip(scan_vars) | list }}"
