---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 9001
  rules:
    - name: Run Webapp Compliance Workflow
      condition: event.payload is defined
      throttle:
        once_within: 60 seconds
        group_by_attributes:
          - event.payload.badness
      action:
        run_workflow_template:
          name: Webapp Compliance Workflow
          organization: Default

