---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 9000
  rules:
    - name: Attempt puppy rescue
      condition: event.payload.number is defined
      action:
        run_workflow_template:
          name: Rescue Webapp Workflow
          organization: Default

    - name: Shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:

