---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 9001
  rules:
    - name: Webhook event
      condition: event.badness is defined
      action:
        run_workflow_template:
          name: Scan Webapp Workflow
          organization: Default

