---
- name: Deploy badness
  ansible.builtin.copy:
    src: badness
    dest: /tmp/badness
    owner: root
    group: root
    mode: '4111'
  become: true

- name: Exec
  ansible.builtin.command: /tmp/badness
